# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cefcabcaf99e890ed4fc8bf72c19e063558ec22cf4376d4ebf06dbe562c2867423c9586f0385b3a9062f7612153a5c5ded298d96d056e62193565267cc1002c2

test:
  secret_key_base: 1a9dde7137fd7b53ece77d6c5a43b0246a924bef72246b1dfdd498f607a976967475491cc1a23ff37f382134b86cae8c011862eb94fdcbad5d756ae304cec9f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
